dfsa
emil-yarmokhin/learning-common pull request #3
Opened 2020-10-09 16:02 UTC by emil-yarmokhin

fsda

2020-10-09 16:02 UTC, vitali-kviatkouski approved these changes

2020-10-09 16:02 UTC, vitali-kviatkouski requested changes
1

2020-10-14 14:44 UTC, emil-yarmokhin commented
В этой ветке последний коммит под заголовком "Пытаюсь разобраться", там решены две задачи.

2020-10-16 15:50 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/tasks_linear programs
> +        int a = 1;
разбей на отдельные java файлы

2020-10-16 16:14 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/tasks_linear programs
> +            System.out.println(z); // Task 1
delete debug info

2020-10-19 04:26 UTC, emil-yarmokhin commented
Виталий, я разбил задания на части, как ты и сказал. Заодно и пересмотрел решения. Посмотри.

2020-10-23 11:51 UTC, emil-yarmokhin commented
Branching и Linear Programs готовы к окончательной проверке

2020-10-23 12:08 UTC, vitali-kviatkouski approved these changes

2020-10-23 12:08 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/Branching/BranchingTask1.java
> +        if ((a <= 0) || (b <= 0) || (c <= 0)) {
optional: 1) скобки необязательны, посмотри приоритеты операторов 2) раз уж a,b заданы как константы, то врядли они будут <= 0

2020-10-23 12:08 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/Branching/BranchingTask3.java
> +            System.out.println(" через параметрическое уравнение прямой.");
optional: длинные строки лучше просто разбивать конкатенацией а не делать 2 вызова печати

2020-10-23 12:08 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/Branching/BranchingTest4.java
> +public class BranchingTest4 {
это лишний файл?

2020-10-23 12:08 UTC, vitali-kviatkouski commented on Learn/Basics of software code development/Branching/BranchingTask5.java
> +            System.out.println(result);
для будущих тасок печатай более осмысленное выражение например "для x=3 вычисленный y=?"

2020-10-23 12:08 UTC, vitali-kviatkouski commented on Learning IDEA/src/LinearProgramsTask1.java
> +public class LinearProgramsTask1 {
дубликаты файлов

2020-10-23 12:23 UTC, merged