Выполненные задания 1-2 из 1 секции модуля "Алгоритмизация"
emil-yarmokhin/learning-common pull request #9
Opened 2020-11-04 11:30 UTC by emil-yarmokhin

Начинаю заливать задания по 2 модулю из первой секции

2020-11-17 15:18 UTC, vitali-kviatkouski requested changes

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +            count = 1;
если ты перенесешь объявление переменной внутрь одного из циклов не нужно будет его очищать каждый раз

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                    c[i] = count;
можно вообще просто же делать c[i]++

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                    b[j] = a[j];
а это вообще зачем?

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                maxTimes = c[i];
это можно вынести за пределы цикла в объявление переменной

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask8.java
> +public class OdArraysTask8 {
approved

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask7.java
> +            if (i >= 1) {
заполнение массива слишком сложно, можно ли упростить?

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask6.java
> +public class OdArraysTask6 {
approved

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask5.java
> +public class OdArraysTask5 {
программа точно делает то что написано в условии?

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask4.java
> +public class OdArraysTask4 {
approved. подумай как переделать программу следуя принципу "объявлять переменную как можно ближе к месту использования"

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask3.java
> +public class OdArraysTask3 {
approved

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask2.java
> +public class OdArraysTask2 {
approved

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask10.java
> +public class OdArraysTask10 {
approved

2020-11-17 15:18 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask1.java
> +public class OdArraysTask1 {
approved

2020-11-17 15:33 UTC, emil-yarmokhin commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask4.java
> +public class OdArraysTask4 {
Не понимаю, о какой переменной идёт речь

2020-11-17 16:22 UTC, emil-yarmokhin commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +            count = 1;
После всех переносов, и иных методов проб и ошибок... Вернее, после постоянных ошибок в подсчёте, я нашёл оптимальным оставить мир этого хрупкого кода в этой части нетронутым.
Или же настаиваешь?

2020-11-17 16:23 UTC, emil-yarmokhin commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                    c[i] = count;
Хрупкий мир.

2020-11-17 16:23 UTC, emil-yarmokhin commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                    b[j] = a[j];
Убрал 21 строку.

2020-11-17 18:24 UTC, emil-yarmokhin commented on Learn/Learning EPAM/src/Section2Algorithmization/OdArrays/OdArraysTask9.java
> +                maxTimes = c[i];
Вынес за пределы цикла в объявление переменной.

2020-12-01 15:38 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/ArraysOfArrays/AOATask16.java
> +    public static void main(String[] args) {
approved

2020-12-01 15:41 UTC, vitali-kviatkouski commented on Learn/Learning EPAM/src/Section2Algorithmization/Sorting/SortingTask1.java
> +        for (int i = 0; i < c.length; i++) {
количество циклов зашкаливает - можно обойтись одним: подумай о правиле формирования номера индекса исходного массива (a / b) в зависимости от номера индекса целевого (с) массива

2020-12-02 14:39 UTC, merged